HABITS = [
    {
        "id":        "meditation",
        "label":     "Meditate",
        "group":     "Mind",
        "freq":      "daily",
        "criterion": "10+ minutes, eyes closed, no phone",
        "active":    True,
    },
    {
        "id":        "reading",
        "label":     "Read",
        "group":     "Mind",
        "freq":      "daily",
        "criterion": "30+ minutes of a book (not articles)",
        "active":    True,
    },
    {
        "id":        "exercise",
        "label":     "Exercise",
        "group":     "Body",
        "freq":      "daily",
        "criterion": "30+ minutes of intentional movement",
        "active":    True,
    },
    {
        "id":        "stretching",
        "label":     "Stretch",
        "group":     "Body",
        "freq":      "daily",
        "criterion": "10+ minutes of stretching or mobility work",
        "active":    True,
    },
    {
        "id":        "long_walk",
        "label":     "Long walk",
        "group":     "Body",
        "freq":      "weekly",
        "criterion": "60+ minute walk outdoors",
        "active":    True,
    },
]
